### ISSUE TITLE
Hashing into the field

### ISSUE THREAD

**Issue by ebfull** [zkcrypto/jubjub#10]
Take a 64-byte representation and reduce modulo `q` or `r`.

**Comment by decentralisedkev** [comment]
What about hashing arbitrary data to a Point ?

A vartime implementation that I think can work for hashing to an extended point is:

Let digest = 512 bit hash (This is the hash of the arbitrary data)

Set v = Fq::from_bytes_wide(digest)

Set z = Fq::one()

u^2 = (v^2 - 1) / (v^2 * D + 1) 

Using Legendre, check for QNR. If this is the case, then increment v by one and start again.
Once a value is found, calculate the sqrt and determine the sign of u.

Set t1 = u
Set t2 = v

The try-and-increment method was modified (no k, but I still think it's vartime) from: Pg2 https://eprint.iacr.org/2009/226.pdf . They also mention that if you make the calculation for Legendre constant time, and then set a security parameter k and only exiting from the loop after k is exceeded, then it would be const time.

**Comment by ebfull** [comment]
Point serialization would be another issue. In Zcash we don't actually need a hash that always produces a point, but other software might. It may be something we punt downstream.

**Comment by Eirik0** [comment]
https://github.com/zkcrypto/jubjub/pull/15
